demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^refer/', include('refer.urls')),
    url(r'^admin/', admin.site.urls),
]

# if settings.DEBUG is True:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

refer/urls.py
from django.conf.urls import url

from . import views

app_name = 'refer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^comprehension', views.comprehension, name='comprehension'),
    url(r'^generation', views.generation, name='generation'),
    url(r'^robotics', views.robotics, name='robotics'),
    url(r'^upload', views.file_upload, name='upload'),
    url(r'^refer_using_image_url/', views.upload_image_using_url, name='upload-url'),
]

refer/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible  # only if you need to support Python 2
class ComprehensionJob(models.Model):
  job_id = models.CharField(max_length=1000, blank=True, null=True)
  image = models.CharField(max_length=1000, blank=True, null=True)
  expression = models.CharField(max_length=1000, blank=True, null=True, default="")
  pred_lang_image = models.CharField(max_length=1000, blank=True, null=True)
  pred_comp_image = models.CharField(max_length=1000, blank=True, null=True) 
  pred_segm_image = models.CharField(max_length=1000, blank=True, null=True) 
  createdAt = models.DateTimeField("Time", null=True, auto_now_add=True)

  def __str__(self):
    return self.job_id

refer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.conf import settings

from channels import Group
import uuid
import os
import os.path as osp
import random
import requests
from urlparse import urlparse
import urllib2
import traceback

from refer.utils import log_to_terminal
import refer.constants as constants
from refer.sender import sender_comprehension

# Create your views here.
def index(request, template_name='index.html'):
  return render(request, 'index.html')

def generation(request, template_name='generation.html'):
  return render(request, 'generation.html')

def robotics(request, template_name='robotics.html'):
  return render(request, 'robotics.html')

def comprehension(request, template_name='comprehension.html'):
  socketid = uuid.uuid4()
  if request.method == "POST":
    try:
      img_path = request.POST.get('img_path')
      img_path = urllib2.unquote(img_path)
      expression = request.POST.get('expression')
      socketid = request.POST.get('socketid')

      # abs_image_path = os.path.join(settings.BASE_DIR, str(img_path))
      abs_image_path = settings.BASE_DIR + str(img_path)
      out_dir = osp.dirname(abs_image_path)

      # run the comprehension wrapper
      log_to_terminal(socketid, {'terminal': 'Starting Comprehension job...'})
      response = sender_comprehension(str(abs_image_path), str(expression), str(out_dir), socketid)
    except:
      log_to_terminal(socketid, {'terminal': traceback.print_exc()})
  return render(request, template_name, {'socketid': socketid})


def upload_image_using_url(request):
  if request.method == "POST":
    try:
      socketid = request.POST.get('socketid', None)
      image_url = request.POST.get('src', None)
      demo_type = request.POST.get('type')

      if demo_type == "comprehension":
        dir_type = constants.COMPREHENSION_CONFIG['image_dir']
      elif demo_type == "generation":
        dir_type = constants.GENERATION_CONFIG['image_dir']

      img_name =  os.path.basename(urlparse(image_url).path)
      response = requests.get(image_url, stream=True)

      if response.status_code == 200:
        random_uuid = uuid.uuid1()
        output_dir = os.path.join(dir_type, str(random_uuid))

        if not os.path.exists(output_dir):
          os.makedirs(output_dir)

        img_path = os.path.join(output_dir, str(img_name))

        with open(os.path.join(output_dir, img_name), 'wb+') as f:
          f.write(response.content)

        img_path =  "/" + "/".join(img_path.split('/')[-4:])
         
        return JsonResponse({"file_path": img_path})
      else:
        return HttpResponse("Please Enter the Correct URL.")
    except:
      return HttpResponse("No images matching this url.")
  else:
    return HttpResponse("Invalid request method.")


def file_upload(request):
  if request.method == "POST":
    image = request.FILES['file']
    demo_type = request.POST.get("type")

    if demo_type == "comprehension":
      dir_type = constants.COMPREHENSION_CONFIG['image_dir']
    elif demo_type == "generation":
      dir_type = constants.GENERATION_CONFIG['image_dir']

    random_uuid = uuid.uuid1()
    # handle image upload
    output_dir = os.path.join(dir_type, str(random_uuid))

    if not os.path.exists(output_dir):
      os.makedirs(output_dir)

    img_path = os.path.join(output_dir, str(image))
    handle_uploaded_file(image, img_path)

    img_path =  "/" + "/".join(img_path.split('/')[-4:])
    return JsonResponse({"file_path": img_path})
  else:
    pass

def handle_uploaded_file(f, path):
  with open(path, 'wb+') as destination:
    for chunk in f.chunks():
      destination.write(chunk)

refer/templates/comprehension.html
{% extends 'base.html' %}

<style type="text/css">
    .caption {
    /*display: block;*/
    /*text-align: center;*/
    font-size: 18px !important;
    font-weight: bold;
    }

    #inputCaption, #predictedCaption{
        font-weight: bold;
    }

    .under
    {
    position:absolute;
    /*left:0px;
    top:0px;*/
    z-index:-1;
    }

    .over
    {
    position:absolute;
    /*left:40px;*/
    /*top:10px;*/
    z-index:0;
    mix-blend-mode: multiply;
    }

    .finalImages{
      width: 350px !important;
      height: 350px !important;
      padding: 6px;
    }

    .resultText{
      margin-bottom: 15px !important;
    }
</style>

{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href={% url 'refer:index' %}>UNC Referring Expressions</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href={% url 'refer:index' %}>Home</a></li>
            <li class="active"><a href={% url 'refer:comprehension' %}>Comprehension Demo</a></li>
            <li><a href={% url 'refer:robotics' %}>Robot Demo</a></li>
        </ul>
    </div>
</nav>
{% endblock %}


{% block form %}
<div class="container">
<!--     <div class="page-header">
        <h2 id="userImages"><strong>Try Referring Expression Comprehension on Your Images</strong></h2>
    </div> -->
    <p><font size="3">or Enter image web url:</font></p>
    {% block url_content %}
        {% include 'upload_image_url.html' %}
    {% endblock %}
    <p><font size="3">or Choose a file / Drag a file here:</font></p>
</div>
<div class="container">    
    <form id="my-dropzone" method="post" class="dropzone" action="{% url 'refer:upload' %}" enctype="multipart/form-data">
        <!-- <input type="hidden" id="demoType" name="demo_type" value="">  -->
        <input type="hidden" id="appType" name="type" value="comprehension">
        {% csrf_token %}
        {% include 'form.html' %}
    </form>
</div>

{% endblock %}


{% block result %}
<script type="text/javascript">

var getLocation = function(href) {
    var l = document.createElement("a");
    l.href = href;
    return l;
}

function submitDemoImage(src){
    var img_path = getLocation(src).pathname;
    console.log({"file_path": img_path})
    $("#inputImageAfterUpload").attr('src', img_path);
    $("#ResultDiv").show();
    $("#Expression").val("");
    $("#show-comprehension-result").hide();
    scrollToElement($("#resultHeading"));
}

function submitImageUsingUrl(){
    var src = document.getElementById("image_url").value;
    console.log("Starting the Image Download process");
    $('#comments').prepend('<br>');
    $('#comments').prepend('<li>' + "Starting the Image Download process." + '</li>');
  
    $.ajax({
        type : "POST",
        url  : '{% url 'refer:upload-url' %}',
        data : {'src': src  , 
                'socketid': "{{socketid}}", 
                'csrfmiddlewaretoken': '{{ csrf_token }}', 
                'type': "comprehension"}
            }).done(function(data){
                console.log(data);
                $("#inputImageAfterUpload").attr('src', data["file_path"]);
                $("#ResultDiv").show();
                $("#Expression").val("");
                $("#show-comprehension-result").hide();
                scrollToElement($("#resultHeading"));
    });
};
$("#image_url").keydown(function(e){
    if (e.which === 13){
        $("#image_url_submit_btn").click();
    }
});

$('#image_url').on('paste', function(){
    setTimeout(function(){
        $("#image_url_submit_btn").click();
    }, 0);
});
</script>


<script type="text/javascript">
  // Overriden 
  Dropzone.options.myDropzone = {
    autoProcessQueue: true,
    uploadMultiple: false,
    maxFiles: 10,

    init: function() {
      var myDropzone = this;
      this.hiddenFileInput.removeAttribute('multiple');
      myDropzone.on('success', function(file, data){
        console.log("Dropzone: "+data['file_path']);
        $("#inputImageAfterUpload").attr('src', data['file_path']);
        $("#ResultDiv").show();
        $("#Expression").val("");
        $("#show-comprehension-result").hide();
        scrollToElement($("#ResultDiv"));
      });
    }
  }
</script>

<script type="text/javascript">

function submitImageForComprehension() {
    var expression = $("#Expression").val();
    if (expression == "") {
        alert("Please write down the expression before submitting.")
    }else if (!if_allowed(expression)){
        alert("Your expression contains disallowed words.")
    }else{
        var l = $("#inputImageAfterUpload")[0].src;
        var img_path = getLocation(l).pathname;
        console.log("Ajax submitting image for comprehension...");
        $.ajax({
            type    : 'POST', // define the type of HTTP verb we want to use (POST for our form)
            url     : '{% url 'refer:comprehension' %}', // the url where we want to POST
            data    : { 'img_path': img_path, 
                        'csrfmiddlewaretoken': "{{ csrf_token }}", 
                        'expression': expression, 
                        'socketid': "{{ socketid }}"} // our data object
        })//using done to ensure callback
        .done(function(response) {
            console.log("Ajax call completed successfully.");
        });
    }
}

function if_allowed(expression) {
    var forbid_words = ['bitch', 'nigger', 'negro', 'monkey', 'gorilla', 'asshole', 'fuck', 'twat', 'shit', 'nigga', 'damn']
    var flag = true;
    for (i=0; i<forbid_words.length; i++) {
        if (expression.indexOf(forbid_words[i]) >= 0){
            flag = false;
        }
    }
    return flag;
}

$(document).ready(function(){
  console.log(window.location.host)
  console.log(window.location.pathname)

  var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
  console.log("socket name: " + ws_scheme + '://' + window.location.host + "/chat" + window.location.pathname)
  var socket = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + "/chat" + window.location.pathname);

  socket.onopen = function() {
      console.log("User connected to the socket with socketid "+ "{{socketid }}");
      socket.send("{{ socketid }}");
  }

  socket.onmessage = function(response) {
    console.log("Getting response from the worker.....");
    console.log(JSON.parse(response.data));

    response = JSON.parse(response.data);
    if ("info" in response){
      console.log("Info is there as the key");
    }

    if("result" in response){

      result = JSON.parse(response['result']);
      var d = new Date();
      $("#img1").attr("src",result['pred_lang_image']+"?"+d.getTime());
      $("#img2").attr("src",result['pred_comp_image']+"?"+d.getTime());
      $("#img3").attr("src",result['pred_segm_image']+"?"+d.getTime());
      $("#show-comprehension-result").show();
      scrollToElement($("#show-comprehension-result"));
    }
  }
});

</script>

<div class="container">
    <h2 id="resultHeading" class="center"><strong>Comprehension Results</strong></h2>
    <div>
        <font size="3">Describe the object that you are interested in. For example, "<u>left apple</u>", "<u>man on the left</u>", "<u>girl in yellow shirt</u>", etc.</font>
        <br>
        <font size="3">Note the dataset and our model only supports referring to <a href="http://cocodataset.org/#explore" target="_blank">80 COCO object categories</a>.</font>
        <br>
        <!-- <font size="3">Current model does not support referring to COCO-stuff, like building, sky, sea, etc.</font> -->
    </div>
    <br>
    <div id="ResultDiv" class="row" style="padding-bottom:50px; display:None;">
        <div class="col-md-4" style="padding-bottom: 30px; clear: both;">
            <img class="img-responsive" src="" id="inputImageAfterUpload">
        </div>
        <div class="col-md-7" style="padding-bottom: 30px;">
            <input id="Expression" class="form-control" name="expression" placeholder="Enter the referring expression...(Required)"><br>
            <input type="button" value="Submit" onclick="submitImageForComprehension()" class="btn btn-primary">
        </div>
    </div>

    <div class="row demoImages" style="display:None;" id="show-comprehension-result" >
<!--         <div class="col-md-4">
            <p class="caption" style="font-size: 14 px;" align="center"">Box Localization</p>
            <img src="" class="col-md-12 " id="img2">
        </div> -->
        <div class="col-md-5">
            <p class="caption" style="font-size:24px;" align="center">Comprehension</p>
            <img src="" class="col-md-12 " id="img3">
        </div>
        <div class="col-md-5">
            <p class="caption" style="font-size:24px;" align="center">Language Attention</p>
            <img src="" style="height:200px;"" id="img1">
        </div>
    </div>
</div>
{% endblock %}



</body>
</html>

refer/templates/form.html
<!-- Write the html code for the form that will be used for sending the input to the backend -->
    <div class="dz-message" style="color:#0000;">
      <h4>Drop files here or click to upload.</h4>
    </div>

refer/templates/generation.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>UNC Referring Expressions</title> 
    <meta name="description" content="UNC Referring Expressions">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- customized css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <!-- google jquery -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
    <!-- microsoft jquery -->
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- dropzone -->
    <script src="/static/js/dropzone.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/min/dropzone.min.css">
    <!-- reconnection websocket -->
    <script src="/static/js/reconnecting-websocket.min.js"></script>
</head>

<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href={% url 'refer:index' %}>UNC Referring Expressions</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href={% url 'refer:index' %}>Home</a></li>
            <li><a href={% url 'refer:comprehension' %}>Comprehension</a></li>
            <li class="active"><a href={% url 'refer:generation' %}>Generation</a></li>
        </ul>
    </div>
</nav>

<div class="container">
    <div class="col-md-12 col-xs-12">
        <font size="3">Generation Demo is under construction.</font>
    </div>
</div>

refer/templates/robotics.html
{% load static %}

<style>
p, h1, h2, h3, a{
  font-weight: 300 !important;
  font-family: 'Roboto', sans-serif;
}

body{
  font-family: 'Roboto', sans-serif;
}

p{
  font-size: 16px;
}
.content
{
    width : 1000px;
    padding : 25px 50px;
    margin : 25px auto;
    background-color : #fff;
    box-shadow: 0px 0px 10px #999;
    border-radius: 15px; 
}
.team{
  width: 85%;
  margin-bottom: 15px;
 }
 .member-name{
  cursor: auto;
  margin-top: 5px;
 }

 .img-responsive{
  max-height: 100%;
  display: block;
  height: 150px; 
 }
 .team_div{
  margin-top: 15px;
 }

 #network{
  margin-top: 15px;
 }

 .headings{
  margin-bottom: 15px;
 }
#team_heading{
  margin-bottom: 25px;
}
li a{
  font-size: 16px;
}
.navbar-brand{
  font-size: 18px !important;
}
</style>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>UNC Referring Expressions</title> 
    <meta name="description" content="UNC Referring Expressions">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- customized css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <!-- google jquery -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
    <!-- microsoft jquery -->
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- dropzone -->
    <script src="/static/js/dropzone.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/4.3.0/min/dropzone.min.css">
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href={% url 'refer:index' %}>UNC Referring Expressions</a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href={% url 'refer:index' %}>Home</a></li>
            <li><a href={% url 'refer:comprehension' %}>Comprehension Demo</a></li>
            <li class="active"><a href={% url 'refer:robotics' %}>Robot Demo</a></li>
            <!-- <li><a href={% url 'refer:generation' %}>Generation</a></li> -->
        </ul>
    </div>
</nav>

<div class="content" align="center">
    <div class="page-header">
        <h2 ><strong>SMaRt: <font color="red">S</font>peech-Driven <font color="red">Ma</font>nipulation <font color="red">R</font>obo<font color="red">t</font></strong> </h2>
    </div>
    <div class="col-md-10 col-md-offset-1" align="left">
        <font size="3">
            Controlling robots to do task for human via natural language is one of the most concerned topic in human-robot interaction. 
            In this project, we propose a robot system for executing simple command (pick, place, pour, etc.) on the target object via natural language description.
            Specifically, given a set of objects (cup, bottle, teddy bear, etc.) on a table and a spoken English description, e.g., ``catch me the bottle on the left'', our robotic system will recognize the audio input, comprehend the instruction, localize target objects, and perform the manipulation task. 
            We name the system SMaRt: Speech-Driven Manipulation Robot.
        </font>
    </div>
    <br>
    <div class="col-md-10 col-md-offset-1" align="center">
        <h3 ><strong>Demo 1</strong></h3>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/x65KTkdOqAM" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
    <div class="col-md-10 col-md-offset-1" align="center">
        <h3 ><strong>Demo 2</strong></h3>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/Me-pKSmopdg" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
    <br>
    <div class="col-md-10 col-md-offset-1" align="center">
        <h3 ><strong>Demo 3</strong></h3>
        <iframe width="560" height="315" src="https://www.youtube.com/embed/6zOPY1CK434" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
    <br>
    <br>
    <div class="col-md-10 col-md-offset-1" align="center">
        <h3 ><strong>Techniqual Report Coming Soon...</strong></h3>
    </div>
    <img src="/media/images/setup.jpg" height="300"></img>
</div>
    

<!-- <div class="content" align="center">
    <div class="page-header">
        <h2 ><strong>SMaRT: Speech-driven Manipulation Robot</strong> </h2>
    </div>
    <div class="col-md-10 col-md-offset-1" align="left">
        <font size="3">
            Controlling robots to do task for human via natural language is one of the most concerned topic in human-robot interaction. 
            In this project, we propose a robot system for executing simple command (pick, place, pour, etc.) on the target object via natural language description.
            Specifically, given a set of objects (cup, bottle, teddy bear, etc.) on a table and a spoken English description, e.g., ``catch me the bottle on the left'', our robotic system will recognize the audio input, comprehend the instruction, localize target objects, and perform the manipulation task. 
            We name the system SMaRt: Speech-Driven Manipulation Robot.
        </font>
    </div>
    <br>

</div> -->
    
</body>
</html>

refer/templates/upload_image_url.html
    
<div class="form-group">
    <input type="url" class="form-control col-sm-6" id="image_url" placeholder="Enter Image URL">
<button onClick="submitImageUsingUrl();" id="image_url_submit_btn" class="btn btn-default btn-primary" style="margin-top: 10px; margin-bottom: 10px;"> Submit </button>
</div>
 